# Generated by Django 5.0.6 on 2025-11-13 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('ciudad', models.CharField(max_length=80)),
                ('estado', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(max_length=80)),
                ('ciudad', models.CharField(max_length=80)),
                ('costo_inscripcion', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descripcion', models.TextField(blank=True)),
                ('num_juegos_estimados', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('UPCOMING', 'Próximo'), ('DONE', 'Realizado')], default='UPCOMING', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='torneos.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('cancha', models.CharField(blank=True, max_length=50)),
                ('marcador_a', models.PositiveIntegerField(default=0)),
                ('marcador_b', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programado'), ('PLAYED', 'Jugado')], default='SCHEDULED', max_length=10)),
                ('equipo_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_como_a', to='torneos.team')),
                ('equipo_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_como_b', to='torneos.team')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='torneos.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable_nombre', models.CharField(max_length=120)),
                ('responsable_telefono', models.CharField(max_length=20)),
                ('responsable_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='torneos.team')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='torneos.tournament')),
            ],
            options={
                'unique_together': {('torneo', 'equipo')},
            },
        ),
    ]
